Removed curl dependecy with reqwest
nathanbabcock/ffmpeg-sidecar pull request #48
Opened 2024-10-11 20:25 UTC by VirtualPirate

**Steps I have taken:**

- Used the reqwest blocking feature to download files .

**Potential Concerns:**

- Currently, the ffmpeg is not downloaded using streaming
- To stream download the file, I think we have to create async download function. ( I personally didn't wanted to go for the async thing, becauase the whole library is not using async )
- For the download progress feature, we need to stream download the file, which is not done in this PR.

**Personal Feelings ( My Personal Opinion only )**

- I think the download progress feature should not be a part of this library, just feels it is out of scope of this library's utility, users can implement their own download progress feature or use another library for it .

Maintainer, feel free to suggest different approach ..

2024-10-11 20:25 UTC, VirtualPirate commented
#47

2024-10-12 14:00 UTC, nathanbabcock requested changes
1 small comment otherwise LGTM 🔥

2024-10-12 14:00 UTC, nathanbabcock commented on src/download.rs
> -/// Invoke cURL on the command line to download a file, returning it as a string.
Let's keep both this function and `curl_to_file` for now, but mark them both as [`#[deprecated]`](https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-deprecated-attribute). And then in the next major version release we can fully remove them.

2024-10-12 14:16 UTC, nathanbabcock approved these changes
@VirtualPirate TYVM! 🙌

2024-10-12 14:16 UTC, merged